version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    links:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
  worker:
    build: .
    command: bundle exec rake environment resque:work QUEUE=*
    volumes:
      - .:/myapp
    links:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
  db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis:6
    ports:
      - "6379"
